name: Verify PR

permissions:
  issues: write
  checks: write
  contents: write
  pull-requests: write
  id-token: write

on:
  push:
  pull_request:
  merge_group:

jobs:
  build:
    name: 🧪 Verify
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: 📝 Set up node
        uses: meza/action-setup-node-pnpm@a2f4240b2835ddfaeb13b353e996e93832b5f47c # main
        with:
          install: false

      - name: 📦 Install Dependencies
        run: pnpm install --prefer-offline --no-frozen-lockfile

      - name: 🔬 Lint
        run: pnpm lint:ci

      - name: 🧪 Test
        run: exit 0

      - name: 📦 Build
        run: pnpm build

      - name: Semantic Release
        run: pnpm release
        env:
          GITHUB_TOKEN: ${{ github.token }}
